app/views.py
from flask import Blueprint, request, flash, redirect, render_template
from flask import Flask
from app.models import Event, Comment, User, ticketOrder
from flask_login import login_required, current_user
from .forms import FindEventForm, CreateEventForm, BuyTicket
from .auth import session
from . import db
from sqlalchemy.orm.attributes import flag_modified
 
 # Create a blueprint
bp = Blueprint('main', __name__, template_folder='templates')


@bp.route('/')
@bp.route('/index')
def index():
    #Get list of all events
    allEvent = Event.query.all()
    return render_template('index.html', allEvent=allEvent)


# If users get a 404 or 500 error load the corressponding error page
@bp.errorhandler(404)
def page_not_found():
    return render_template('404.html')

@bp.errorhandler(500)
def page_not_found():
    return render_template('500.html')


#@bp.route('/event_info_page', methods=['GET', 'POST'])
#def event_info_page():
#    def get_choices():
#        return Event.query.order_by(Event.eventName)
#
#    form = FindEventForm()
#    choices = get_choices
#    form.event_id.choices = choices
#    
#    if form.validate_on_submit():
#        event = Event.query.filter_by(eventName=form.data).first()
#        event_id = event.id
#        event_user = event.userId
#        event_name = event.eventName
#        event_date = event.eventDate
#        event_t_type = event.ticketTypes
#        event_desc = event.description
#        event_stat = event.eventStatus
#        event_comments = event.comments
#        event_orders = event.ticketOrders
#    return render_template('event_info_page.html', form=form)


@bp.route('/event_creation', methods=['GET', 'POST'])
def event_creation():
    if current_user.is_authenticated:
        form = CreateEventForm()
        if form.validate_on_submit():
            file = request.files['file']
            # If input data meets all validators and user is logged in send
            # all new event data to a database
            event = Event(
                creatorUserId = session['UserID'],
                eventName = form.event_name.data,
                eventDate = form.event_date.data,
                eventTime = form.event_time.data,
                description = form.event_description.data,
                ticketPrice = form.ticket_price.data,
                numberOfTickets = form.number_of_tickets.data,
                eventStatus = form.event_status.data,
                eventImg = file.read()
            )
            db.session.add(event)
            db.session.commit()
            return redirect('/index')
    else:
        flash('Not logged in')
        return redirect('/login')
    return render_template('event_creation.html', title = 'EVENT_CREATION', form=form)



#@bp.route('/booking_history', methods=['GET', 'POST'])
#def booking_history():
#    bookings = []
#    if "UserID" in session:
#        tickets = ticketOrder.query.filter_by(session['UserID']).all()
#        for ticket in tickets:
#            bookings.append(ticket)
#    else:
#        flash('Not logged in')
#        return redirect('/login')
#    return render_template('booking_history.html', **locals())



@bp.route('/my_events', methods=['GET', 'POST'])
def my_events():
    # Check user is logged in, and if so fetch all event data from the database
    # that matches with their user id
    if current_user.is_authenticated:
        myName = User.query.filter_by(id=current_user.id)
        myEvent = Event.query.filter_by(creatorUserId=current_user.id).all()
    else:
        flash('Not logged in')
        return redirect('/login')
    return render_template("my_events.html", myName=myName, myEvent=myEvent)


# Create dynamic url to fetch details on any event
@bp.route('/event/<int:eventId>', methods=['GET', 'POST'])
def event(eventId):
    form=BuyTicket()
    chosenEvent = Event.query.filter_by(id=eventId)
    return render_template("event_info_page.html", chosenEvent=chosenEvent, form=form)

app/templates/Event_Creation.html
{% extends 'base.html' %}

{% import "bootstrap/form.html" as wtf %}
{% block content %}
   <main>
<!--Generic event picture-->
<!--First row, picture and event details-->
<form action = "" method = "post" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  <div class="row align-items-start">
    <div class="col-md-4" style="padding-top: 20px;">
        <img src="{{ url_for('static', filename='Open sign.jpg')}}" height="400" width="400">
    </div>
    <!--Event Details-->
    <div class="col-md-4" style="padding-top:20px; padding-bottom: 20px;">
      <h6 style="font-size: 32px;">Event Details</h6>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Event Name</label><br>
        {{ form.event_name(size=32) }}
        {% for error in form.event_name.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">DD/MM/YYYY</label><br>
        {{ form.event_date(size=32) }}
        {% for error in form.event_date.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Event Start Time</label><br>
        {{ form.event_time(size=32) }}
        {% for error in form.event_time.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Description</label><br>
        {{ form.event_description(size=32) }}
        {% for error in form.event_description.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Event Status</label><br>
        {{ form.event_status(size=6) }}
        {% for error in form.event_status.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Ticket Price</label><br>
        {{ form.ticket_price(size=32) }}
        {% for error in form.ticket_price.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Number of Tickets Availiable</label><br>
        {{ form.number_of_tickets(size=32) }}
        {% for error in form.number_of_tickets.errors %}
        <span style="color:red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInput" class="form-label">Upload Event Image</label><br>
        <input type="file" name="file">
      </div>
      <div style="padding-bottom: 10px ;">
      {{form.submit()}}
    </div>
  </div>
	</form>
</main>
{% endblock %}

app/templates/PaymentConfirmation.html
{% extends "base.html" %}
{% import "bootstrap/form.html" as wtf %}

{% block content %}

<div class="container p-0">
    <div class="card px-4">
        <p class="h8 py-3">Payment Details</p>
        <div class="row gx-3">
            <div class="col-12">
                <div class="d-flex flex-column">
                    <p class="text mb-1">Person Name</p>
                    <input class="form-control mb-3" type="text" placeholder="Name" value="Barry Allen">
                </div>
            </div>
            <div class="col-12">
                <div class="d-flex flex-column">
                    <p class="text mb-1">Card Number</p>
                    <input class="form-control mb-3" type="text" placeholder="1234 5678 435678">
                </div>
            </div>
            <div class="col-6">
                <div class="d-flex flex-column">
                    <p class="text mb-1">Expiry</p>
                    <input class="form-control mb-3" type="text" placeholder="MM/YYYY">
                </div>
            </div>
            <div class="col-6">
                <div class="d-flex flex-column">
                    <p class="text mb-1">CVV/CVC</p>
                    <input class="form-control mb-3 pt-2 " type="password" placeholder="***">
                </div>
            </div>
            <div class="col-12">
                <div class="btn btn-primary mb-3">
                    <span class="ps-3">Pay $243</span>
                    <span class="fas fa-arrow-right"></span>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Landing page</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
  <div class="p-3 mb-2 bg-dark text-white">
    <header>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg" style="background-color: #a8a5a5" >
      <div class="container-fluid">
        <a class="navbar-brand" href="/index">
          <img src="{{ url_for('static', filename='Nav Thumbnail.jpg')}}" alt="Nav Thumbnail" width="60" height="48">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
          <span class="navbar-toggler-icon" ></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/index" style="color:black">Home</a>
            </li>
            <!--<li class="nav-item">
              <a class="nav-link" href="/event_info_page" style="color:black">Events</a>
            </li>-->
            <li class="nav-item">
              <a class="nav-link" href="/my_events" style="color:black">My Events</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:black"> More Options
              </a>
              <!-- If user is logged out display login and register butons, else if user is logged in
              display a logout option -->
              <ul class="dropdown-menu">
                <!--<li><a class="dropdown-item" href="/booking_history">Booking History</a></li>-->
                <li><a class="dropdown-item" href="/event_creation">Create Event</a></li>
                {% if current_user.is_anonymous %}
                <li><a class="dropdown-item" href="/login">Login</a></li>
                <li><a class="dropdown-item" href="/register">Register</a></li>
                {% else %}
                <li><a class="dropdown-item" href="/logout">Logout</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search" >
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit" style="color:black">Search</button>
          </form>
        </div>
      </div>
    </nav>

<body>
    <!-- Header -->
    <header>

        <!-- Navbar -->
        <nav>
        </nav>

        {% block header %}
        {% endblock %}

    </header>

    {% block content %}
    {% endblock %}


    <!--Footer-->
    <footer>
        <div class="container-fluid">
        <div class = "row">
            <div class="card text-bg-dark">
            <img src="{{ url_for('static', filename='Footer Pic.jpg')}}" class="card-img" alt="..." height="250">
            <div class="card-img-overlay" style="color:white">
                <h5 class="card-title">About</h5>
                <p class="card-text"><li>
                  <p>FAQ</p>
                  <p>Contact Us</p>
                  <p>Privacy & Terms</p>
                </li></p>
                <p class="card-text"><small>Last updated 3 mins ago</small></p>
            </div>
            </div>
        </div>
        </div>
    </footer>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </div>
    </body>


</html>

app/templates/booking_history.html
{% extends 'base.html' %}

{% import "bootstrap/form.html" as wtf %}
{% block content %}
<!--Page Header-->
   <main>
    <div class="row" style="padding-bottom: 40px;">
        <div class="col-12 offset-md-4">
            <h1>Booking History</h1>
        </div>
    </div>


    <!--Booking history images plus tables, images link to event info page-->
    <div class="row">
        <div class="col-md-6 offset-md-3" style="padding-bottom: 70px;">
            <table class="table-dark">
              {{ % for booking in bookings % }}
                <tr>
                    <td><a href="/event_info_page/{{booking.eventId}}">
                        <img src="{{Event.query.get(booking.eventId).eventImg}}" height="100" width="100"></a></td>
                    <td><p>Ticket Type: {{booking.ticketType}} <br> Quantity: {{booking.quantity}} <br> Booking ID: {{booking.id}}</p></td>
                </tr>
                {{ % endfor % }}
            </table>
        </div>
    </div>



   </main>
{% endblock %}

app/templates/event_info_page.html
{% extends 'base.html' %}

{% import "bootstrap/form.html" as wtf %}
{% block content %}
<!--Main Event Picture-->
   <main>
  <div class="row"> 
    <div class="col-md-4">
      <img src="{{ url_for('static', filename='Maggie Olsen.jpg')}}" width="400">
      <!--Other pictures in table-->
      <table>
        <tr>
          <td><img src="{{ url_for('static', filename='Piano and hands.jpg')}}" width="200" height="200"></td>
          <td><img src="{{ url_for('static', filename='Trumpets.jpg')}}" width="200" height="200"></td>
        </tr>
        <tr>
          <td><img src="{{ url_for('static', filename='Soundboard.jpg')}}" width="200" height="200"></td>
          <td><img src="{{ url_for('static', filename='Microphone.jpg')}}" width="200" height="200"></td>
        </tr>
        <tr>
          <td><img src="{{ url_for('static', filename='Marshall speaker.jpg')}}" width="200" height="200"></td>
          <td><img src="{{ url_for('static', filename='Open sign.jpg')}}g" width="200" height="200"></td>
        </tr>
      </table> 
    </div>
    <!--Event Text-->
      <div class="col-md-6" style="padding-top: 20px;">
        <!--Headline-->
            {% for item in chosenEvent %}
              <h1 style="font-weight: bold ;">{{ item.eventName }} Is Happening {{ item.eventDate }} At {{ item.eventTime }}</h1>
              <h4>Status: {{ item.eventStatus }}</h2><br><hr><br><br>
              <p>{{ item.description }}</p><br><hr><br><br>
              <h3>Price : {{ item.ticketPrice }}</h3>
              <p>Tickets Remaining: {{ item.numberOfTickets }}</p>
            {% endfor %}
              <form action="" method="post">
                  {{ form.hidden_tag() }}
                  <label for="exampleInput" class="form-label">Purchase Amount</label><br>
                    <p>
                    {{ form.ticket_amount(size=32) }}
                    {% for error in form.ticket_amount.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                  </p>
                  <div style="padding-bottom: 10px ;">
                    <label for="exampleInput" class="form-label">Buy Tickets</label><br>
                    {{form.submit()}}
                  </div>
              </form>
            <!--Generic Text-->
      </div>
  </div>


  <!--Comment Section-->
<div class="row">
  <div class="col-md-4">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{{ url_for('static', filename='Comment 1.png')}}" class="d-block w-100" alt="..." height="200">
        </div>
        <div class="carousel-item">
          <img src="{{ url_for('static', filename='Comment 2.png')}}" class="d-block w-100" alt="..." height="200">
        </div>
        <div class="carousel-item">
          <img src="{{ url_for('static', filename='Comment 3.png')}}" class="d-block w-100" alt="..." height="200">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

  <div class="col-md-4" style="padding-top: 30px;">
    <h3>Let us know your thoughts on this event</h3>
    <button type="button" class="btn btn-light" style="--bs-btn-padding-y: .60rem; --bs-btn-padding-x: .20rem; --bs-btn-font-size: 1.4rem;">Leave a comment</button>
  </div>
</div>
   </main>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %} 


<main>
  <div class="container-fluid">
    <div class = "row">
      <div class = "col-lg-8">

        <!--Carousel-->
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel"  style= "padding-top: 10px;">
          <div class="carousel-inner">
            <div class="carousel-item active"><a href="/index">
              <img src="{{ url_for('static', filename='Carousel Pic 1.jpg')}}" class="d-block w-100" alt="Concert" height="600" width="750px">
              <div class="carousel-caption d-none d-md-block">
              </div>
            </a></div>
            <div class="carousel-item"><a href="/index">
              <img src="{{ url_for('static', filename='Carousel Pic 2.jpg')}}" class="d-block w-100" alt="Guitarist" height="600" width="750px">
              <div class="carousel-caption d-none d-md-block">
              </div>
            </a></div>
            <div class="carousel-item"><a href="/index">
              <img src="{{ url_for('static', filename='Carousel Pic 3.jpg')}}" class="d-block w-100" alt="DJ" height="600" width="750px">
              <div class="carousel-caption d-none d-md-block">
              </div>
            </a></div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>

    <!--Article with events-->
      <div class = "container-fluid col-sm-4 " style="padding-top: 10px; padding-bottom: 10px;">
        <article class="forecast"> <a href = "/index">
          <div class="card" style="width: 18rem;"> 
            <img src="{{ url_for('static', filename='Maggie Olsen.jpg')}}" class="card-img-top" alt="..." height="200">
            <div class="card-img-overlay" style = "color:white">
              <h6 class="card-text" >Maggie Olsen Nov 24th</h6>
              <p>Booked</p>
            </div>
          </div></a>
        </article>
        <article class="day-forecast"> <a href="/index">
          <div class="card" style="width: 18rem;">
            <img src="{{ url_for('static', filename='Jimmy Young.jpg')}}" class="card-img-top" alt="..." height="200">
            <div class="card-img-overlay" style = "color:white">
              <h6 class="card-text">Jimmy Young Dec 1st</h6>
              <p>Upcoming</p>
            </div>
          </div></a>
        </article>
          <article class="day-forecast"> <a href="/index">
            <div class="card" style="width: 18rem;">
              <img src="{{ url_for('static', filename='Ivan Right.jpg')}}" class="card-img-top" alt="..." height="200">
              <div class="card-img-overlay" style = "color:white">
                <h6 class="card-text">Ivan Right Dec 10th</h6>
                <p>Upcoming</p>
              </div>
            </div></a>
          </article>
        </article>
    </div>
  </div>
</div>
<!-- Display all events currently in the database -->
<h3>All Upcoming Events</h3><hr><br><br>
<div>
  <ul style="list-style-type: none;">
    {% for item in allEvent %}
          <a href = "{{ url_for('main.event', eventId = item.id) }}" style="text-decoration:none; color:white">
            <img src="{{ url_for('static', filename='placeholder.jpg')}}" height="200">
            <li>{{ item.eventName }} &nbsp;&nbsp;{{ item.eventDate }}</li>
            <li>Status: {{ item.eventStatus }}</li>
          </a>
      <br><br><hr><br><br>
    {% endfor %}
  </ul>
  </div>
    </main>
    {% endblock %}

app/templates/login.html
 {% extends 'base.html' %}

{% block header %}


{% endblock %}

{% block content %} 

 <div class="col-4" style="padding-bottom: 200px;">
        <form action="" method="post" novalidate>
          {{ form.hidden_tag() }}
          <h4>Enter Email and Password</h4>
          <div style="padding-bottom: 20px;"></div>
          <div class="mb-3">
            <p>
              {{ form.username.label }}<br>
              {{ form.username(size=32) }}<br>
              {% for error in form.username.errors %}
              <span style="color:red;">[{{ error }}]</span>
              {% endfor %}
            </p>
          </div>
          <div class="mb-3">
            <p>
              {{ form.password.label }}<br>
              {{ form.password(size=32) }}<br>
              {% for error in form.password.errors %}
              <span style="color:red;">[{{ error }}]</span>
              {% endfor %}
            </p>
          </div>
          <p>{{ form.rememberMe() }}  {{ form.rememberMe.label }}</p><br>
          <p>{{ form.submit() }}</p>
      </form>
      <p>New User? <a href="/register" style="text-decoration: none;">Click Here to Register!</a></p>
    </div>


{% endblock %}

app/templates/my_events.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %} 

<ul style="list-style-type: none; font-size: 32px; padding-top: 5px;">
  {% for item in myName %}
        <li>{{ item.username }}'s Events</li><br>
{% endfor %}
</ul>
<div>
<ul style="list-style-type: none;">
  {% for item in myEvent %}
        <a href = "{{ url_for('main.event', eventId = item.id) }}" style="text-decoration:none; color:white">
          <li>Name: {{ item.eventName }} &nbsp;&nbsp;  At: {{ item.eventTime }}&nbsp;&nbsp; On: {{ item.eventDate }}</li>
          <li>Description: {{ item.description }}</li>
          <li>Tickets Left: {{ item.numberOfTickets }}</li>
          <li>Status: {{ item.eventStatus }}</li>
        </a>
    <br><br><hr><br><br>
  {% endfor %}
</ul>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% import "bootstrap/form.html" as wtf %}
{% block content %}
 {{ form.hidden_tag() }}
 <div class="col-4" style="padding-top: 2.5%; padding-bottom:2.5%">
        <form action="" method="post">
          {{ form.hidden_tag() }}
            <h4>Enter Personal Details</h4>
            <div style="padding-bottom: 20px;"></div>
            <div class="mb-3">
              <p>
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}  <br>
                {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
                </p>
            </div>
		        <div class="mb-3">
              <p>
                {{ form.email.label }}<br>
                {{ form.email(size=32) }}<br>  
                {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
              </p>
            </div>
            <div class="mb-3">
              <p>
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}  <br>
                {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
                </p>
             </div>
		        <div class="mb-3">
              <p>
              {{ form.confirm.label }}<br>
              {{ form.confirm(size=32) }}  <br>
              {% for error in form.confirm.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
              </p>
            </div>
		        <div class="mb-3">
              <p>
                {{ form.address.label }}<br>
                {{ form.address(size=32) }} <br> 
                {% for error in form.address.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
              </p>
            </div>
		        <div class="mb-3">
              <p>
                {{ form.contactNumber.label }}<br>
                {{ form.contactNumber(size=32) }}  <br>
                {% for error in form.contactNumber.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
              </p>

            </div>
            <p>{{ form.submit() }}</p>
          </form>
</div>
	
{% endblock %}

app/templates/user.html
{% include "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body %}

<div class="page-header">
    <h4>{{heading}}</h4>
</div>



<div class="container-fluid">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

</div>



<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
    {{wtf.render_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4">
    <p>New user? <a href="{{ url_for('register') }}">Click here to register</a>.</p>
</div>
{% endif %}

{% endblock %}